"""empty message

Revision ID: 0c5005301c0a
Revises: 
Create Date: 2020-08-02 09:55:46.512828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5005301c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('admin_id', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'admin', ['admin_id'])
    op.create_unique_constraint(None, 'admin', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_constraint(None, 'admin', type_='unique')
    op.drop_column('admin', 'admin_id')
    # ### end Alembic commands ###
