"""empty message

Revision ID: 7404a61e25c8
Revises: 
Create Date: 2020-08-16 09:37:35.398053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7404a61e25c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_image', sa.LargeBinary(), nullable=True),
    sa.Column('about_image', sa.LargeBinary(), nullable=True),
    sa.Column('carousel_images', sa.PickleType(), nullable=True),
    sa.Column('volunteers', sa.PickleType(), nullable=True),
    sa.Column('carousel_info', sa.PickleType(), nullable=True),
    sa.Column('about_info', sa.Text(), nullable=True),
    sa.Column('nav_bar', sa.PickleType(), nullable=True),
    sa.Column('header_info', sa.PickleType(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    op.drop_table('config')
    op.drop_table('admin')
    # ### end Alembic commands ###
